# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            NA48
tagline:          ''
description:      'This is a test of Jekyll, Hyde and Poole.'
url:              http://mattleblanc.github.io/blog/
baseurl:          /

author:
  name:           'Matt LeBlanc'
  url:            https://twitter.com/NA_48

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mattleblanc/blog/
