# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            mleblanc
tagline:          ''
description:      'Physics and Wizards.'
url:              http://mattleblanc.github.io/blog/
baseurl:          http://mattleblanc.github.io/blog/

author:
  name:           'Matt LeBlanc'
  url:            https://twitter.com/NA_48

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mattleblanc/blog/
